# Generated by Django 3.2.5 on 2021-09-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(default='Mensaje Vacio'),
        ),
    ]
